services:
  redis-master:
    image: redis:7-alpine
    container_name: lab08-redis-master
    ports:
      - "6380:6379"
    volumes:
      - redis_master_data:/data
    restart: unless-stopped

  redis-replica:
    image: redis:7-alpine
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    restart: unless-stopped

  database:
    image: mysql:5.7
    container_name: lab08-db-v2 
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flashsale_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data_v2:/var/lib/mysql
    restart: unless-stopped

  product-service:
    build: ./services/product-service
    environment:
      - REDIS_URL=redis://redis-master:6379
    depends_on:
      - redis-master
    ports:
      - "8081:8081"

  cart-service:
    build: ./services/cart-service
    environment:
      - REDIS_URL=redis://redis-master:6379
    depends_on:
      - redis-master
    ports:
      - "8082:8082"

  order-service:
    build: ./services/order-service
    environment:
      - REDIS_URL=redis://redis-master:6379
    depends_on:
      - redis-master
    ports:
      - "8083:8083"

  inventory-service:
    build: ./services/inventory-service
    environment:
      - REDIS_URL=redis://redis-master:6379
    depends_on:
      - redis-master
    ports:
      - "8084" # Để trống port host để có thể scale --scale

  user-service:
    build: ./services/user-service
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=flashsale_db
    depends_on:
      - database
    ports:
      - "8085:8085"

volumes:
  redis_master_data:
  db_data_v2:
