events { worker_connections 1024; }
http {
    upstream inventory {
        server inventory-service:8084;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://inventory;
        }
    }
}
